apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-db
spec:
  template:
    metadata:
      name: {{ .Release.Name }}-db
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - {{ .Values.nodeNumber }}
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.container.image }}
        env:
        - name: CONTAINER_NAME
          value: {{ .Release.Name }}
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: ROOT_PASSWORD
        command: ["/bin/sh","-c"]
        args: ["mysql --host=${CONTAINER_NAME} -u root -p${MYSQL_ROOT_PASSWORD} <  /var/lib/mysql/create-db-books.sql"]
        volumeMounts:
        - name: {{ .Release.Name }}-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: {{ .Release.Name }}-persistent-storage
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-pv-claim
      restartPolicy: OnFailure
