apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-db
spec:
  template:
    metadata:
      name: {{ .Release.Name }}-db
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.container.image }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: ROOT_PASSWORD
        command: ["/bin/sh","-c"]
        args: ["mysql -h {{ .Release.Name }} -u root -p${MYSQL_ROOT_PASSWORD} <  /var/lib/mysql/create-db-books.sql"]
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
      restartPolicy: OnFailure
