apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-dump
spec:
  schedule: "0 1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:  
          - name: {{ .Release.Name }}
            image: {{ .Values.container.image }}
            env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: ROOT_PASSWORD
            command: ["/bin/sh","-c"]
            args: ["mysqldump -h {{ .Release.Name }} -u root -p${MYSQL_ROOT_PASSWORD} test > /var/lib/mysql/test.sql"]
            volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
          volumes:
          - name: mysql-persistent-storage
            persistentVolumeClaim:
              claimName: mysql-pv-claim
          restartPolicy: OnFailure
