apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  ports:
  - port: 3306
  selector:
    app: {{ .Release.Name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - image: {{ .Values.container.image }}
        name: {{ .Release.Name }}
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: ROOT_PASSWORD
        ports:
        - containerPort: 3306
          name: {{ .Release.Name }}
        volumeMounts:
        - name: {{ .Release.Name }}-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: {{ .Release.Name }}-persistent-storage
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-pv-claim
