apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-job
spec:
  template:
    metadata:
      name: mysql-job
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        command: ["/bin/sh","-c"]
        args: ["mysqldump -h 10.233.105.79 -u root -p${MYSQL_ROOT_PASSWORD} test > /opt/backup.sql"]
#        command: 
#          - "bin/bash"
#          - "hostname"
#          - "mysql --version"
      restartPolicy: OnFailure
