apiVersion: batch/v1
kind: CronJob
metadata:
  name: mysql-dump
spec:
  schedule: "35 21 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:  
          - name: mysql
            image: andriy900/mysql-andriy:latest
            env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: ROOT_PASSWORD
            command: ["/bin/sh","-c"]
            args: ["mysqldump -h mysql -u root -p${MYSQL_ROOT_PASSWORD} test > /var/lib/mysql/test.sql"]
            volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
          volumes:
          - name: mysql-persistent-storage
            persistentVolumeClaim:
              claimName: mysql-pv-claim
          restartPolicy: OnFailure
